# Generated by Django 4.2.13 on 2024-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_products_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
